using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace BookApi.EntityFrameworkCore.Migrations
{
    /// <inheritdoc />
    public partial class Initial : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Categories",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Image = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Title = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ParentId = table.Column<int>(type: "int", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Categories", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Categories_Categories_ParentId",
                        column: x => x.ParentId,
                        principalTable: "Categories",
                        principalColumn: "Id");
                });

            migrationBuilder.CreateTable(
                name: "LinkObject",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Href = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Method = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Title = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_LinkObject", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Links",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    SelfId = table.Column<int>(type: "int", nullable: true),
                    BooksId = table.Column<int>(type: "int", nullable: true),
                    DynamicContentId = table.Column<int>(type: "int", nullable: true),
                    CategoryId = table.Column<int>(type: "int", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Links", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Links_Categories_CategoryId",
                        column: x => x.CategoryId,
                        principalTable: "Categories",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Links_LinkObject_BooksId",
                        column: x => x.BooksId,
                        principalTable: "LinkObject",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Links_LinkObject_DynamicContentId",
                        column: x => x.DynamicContentId,
                        principalTable: "LinkObject",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Links_LinkObject_SelfId",
                        column: x => x.SelfId,
                        principalTable: "LinkObject",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.InsertData(
                table: "Categories",
                columns: new[] { "Id", "Image", "ParentId", "Title" },
                values: new object[,]
                {
                    { 2, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_category_2.png?format=png&quality=75&w=450", null, "Novels" },
                    { 12, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_category_12.png?format=png&quality=75&w=450", null, "Crime, Thrillers & Mystery" },
                    { 20, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_category_20.png?format=png&quality=75&w=450", null, "Fantasy" },
                    { 24, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_category_24.png?format=png&quality=75&w=450", null, "Science Fiction" },
                    { 27, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_category_27.png?format=png&quality=75&w=450", null, "Romance" },
                    { 34, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_category_34.png?format=png&quality=75&w=450", null, "Comedy & Humour" },
                    { 38, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_category_38.png?format=png&quality=75&w=450", null, "Personal Development" },
                    { 48, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_category_48.png?format=png&quality=75&w=450", null, "Biographies" },
                    { 54, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_category_54.png?format=png&quality=75&w=450", null, "Non-Fiction Books" },
                    { 73, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_category_73.png?format=png&quality=75&w=450", null, "Classics" },
                    { 84, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_category_84.png?format=png&quality=75&w=450", null, "Books for Children" },
                    { 98, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_category_98.png?format=png&quality=75&w=450", null, "Books for Young Adults" },
                    { 112, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_112.jpg?format=png&quality=75&w=450", null, "Svenska" },
                    { 118, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_118.jpg?format=png&quality=75&w=450", null, "Suomi" },
                    { 124, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_124.jpg?format=png&quality=75&w=450", null, "Deutsch" },
                    { 130, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_130.jpg?format=png&quality=75&w=450", null, "Italiano" },
                    { 136, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_136.jpg?format=png&quality=75&w=450", null, "Español" },
                    { 142, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_142.jpg?format=png&quality=75&w=450", null, "Dansk" },
                    { 148, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_148.jpg?format=png&quality=75&w=450", null, "Polski" },
                    { 155, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_category_155.png?format=png&quality=75&w=450", null, "Short Stories, Drama & Poetry" },
                    { 165, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_165.jpg?format=png&quality=75&w=450", null, "Nederlands" },
                    { 166, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_166.jpg?format=png&quality=75&w=450", null, "Français" }
                });

            migrationBuilder.InsertData(
                table: "LinkObject",
                columns: new[] { "Id", "Href", "Method", "Title" },
                values: new object[,]
                {
                    { 1, "https://api.bookbeat.com/api/categories/12", "GET", null },
                    { 2, "https://api.bookbeat.com/api/categories/12/books?offset=0&limit=50", "GET", "Books" },
                    { 3, "https://api.bookbeat.com/api/categoryviews/12?offset=0&limit=50", "GET", null },
                    { 4, "https://api.bookbeat.com/api/categories/13", "GET", null },
                    { 5, "https://api.bookbeat.com/api/categories/13/books?offset=0&limit=50", "GET", "Books" },
                    { 6, "https://api.bookbeat.com/api/categoryviews/13?offset=0&limit=50", "GET", null },
                    { 7, "https://api.bookbeat.com/api/categories/14", "GET", null },
                    { 8, "https://api.bookbeat.com/api/categories/14/books?offset=0&limit=50", "GET", "Books" },
                    { 9, "https://api.bookbeat.com/api/categoryviews/14?offset=0&limit=50", "GET", null },
                    { 10, "https://api.bookbeat.com/api/categories/15", "GET", null },
                    { 11, "https://api.bookbeat.com/api/categories/15/books?offset=0&limit=50", "GET", "Books" },
                    { 12, "https://api.bookbeat.com/api/categoryviews/15?offset=0&limit=50", "GET", null },
                    { 13, "https://api.bookbeat.com/api/categories/16", "GET", null },
                    { 14, "https://api.bookbeat.com/api/categories/16/books?offset=0&limit=50", "GET", "Books" },
                    { 15, "https://api.bookbeat.com/api/categoryviews/16?offset=0&limit=50", "GET", null },
                    { 16, "https://api.bookbeat.com/api/categories/17", "GET", null },
                    { 17, "https://api.bookbeat.com/api/categories/17/books?offset=0&limit=50", "GET", "Books" },
                    { 18, "https://api.bookbeat.com/api/categoryviews/17?offset=0&limit=50", "GET", null },
                    { 19, "https://api.bookbeat.com/api/categories/2", "GET", null },
                    { 20, "https://api.bookbeat.com/api/categories/2/books?offset=0&limit=50", "GET", "Books" },
                    { 21, "https://api.bookbeat.com/api/categoryviews/2?offset=0&limit=50", "GET", null },
                    { 22, "https://api.bookbeat.com/api/categories/5", "GET", null },
                    { 23, "https://api.bookbeat.com/api/categories/5/books?offset=0&limit=50", "GET", "Books" },
                    { 24, "https://api.bookbeat.com/api/categoryviews/5?offset=0&limit=50", "GET", null },
                    { 25, "https://api.bookbeat.com/api/categories/6", "GET", null },
                    { 26, "https://api.bookbeat.com/api/categories/6/books?offset=0&limit=50", "GET", "Books" },
                    { 27, "https://api.bookbeat.com/api/categoryviews/6?offset=0&limit=50", "GET", null },
                    { 28, "https://api.bookbeat.com/api/categories/8", "GET", null },
                    { 29, "https://api.bookbeat.com/api/categories/8/books?offset=0&limit=50", "GET", "Books" },
                    { 30, "https://api.bookbeat.com/api/categoryviews/8?offset=0&limit=50", "GET", null },
                    { 31, "https://api.bookbeat.com/api/categories/11", "GET", null },
                    { 32, "https://api.bookbeat.com/api/categories/11/books?offset=0&limit=50", "GET", "Books" },
                    { 33, "https://api.bookbeat.com/api/categoryviews/11?offset=0&limit=50", "GET", null },
                    { 34, "https://api.bookbeat.com/api/categories/177", "GET", null },
                    { 35, "https://api.bookbeat.com/api/categories/177/books?offset=0&limit=50", "GET", "Books" },
                    { 36, "https://api.bookbeat.com/api/categoryviews/177?offset=0&limit=50", "GET", null },
                    { 37, "https://api.bookbeat.com/api/categories/54", "GET", null },
                    { 38, "https://api.bookbeat.com/api/categories/54/books?offset=0&limit=50", "GET", "Books" },
                    { 39, "https://api.bookbeat.com/api/categoryviews/54?offset=0&limit=50", "GET", null },
                    { 40, "https://api.bookbeat.com/api/categories/160", "GET", null },
                    { 41, "https://api.bookbeat.com/api/categories/160/books?offset=0&limit=50", "GET", "Books" },
                    { 42, "https://api.bookbeat.com/api/categoryviews/160?offset=0&limit=50", "GET", null },
                    { 43, "https://api.bookbeat.com/api/categories/161", "GET", null },
                    { 44, "https://api.bookbeat.com/api/categories/161/books?offset=0&limit=50", "GET", "Books" },
                    { 45, "https://api.bookbeat.com/api/categoryviews/161?offset=0&limit=50", "GET", null },
                    { 46, "https://api.bookbeat.com/api/categories/55", "GET", null },
                    { 47, "https://api.bookbeat.com/api/categories/55/books?offset=0&limit=50", "GET", "Books" },
                    { 48, "https://api.bookbeat.com/api/categoryviews/55?offset=0&limit=50", "GET", null },
                    { 49, "https://api.bookbeat.com/api/categories/56", "GET", null },
                    { 50, "https://api.bookbeat.com/api/categories/56/books?offset=0&limit=50", "GET", "Books" },
                    { 51, "https://api.bookbeat.com/api/categoryviews/56?offset=0&limit=50", "GET", null },
                    { 52, "https://api.bookbeat.com/api/categories/57", "GET", null },
                    { 53, "https://api.bookbeat.com/api/categories/57/books?offset=0&limit=50", "GET", "Books" },
                    { 54, "https://api.bookbeat.com/api/categoryviews/57?offset=0&limit=50", "GET", null },
                    { 55, "https://api.bookbeat.com/api/categories/58", "GET", null },
                    { 56, "https://api.bookbeat.com/api/categories/58/books?offset=0&limit=50", "GET", "Books" },
                    { 57, "https://api.bookbeat.com/api/categoryviews/58?offset=0&limit=50", "GET", null },
                    { 58, "https://api.bookbeat.com/api/categories/59", "GET", null },
                    { 59, "https://api.bookbeat.com/api/categories/59/books?offset=0&limit=50", "GET", "Books" },
                    { 60, "https://api.bookbeat.com/api/categoryviews/59?offset=0&limit=50", "GET", null },
                    { 61, "https://api.bookbeat.com/api/categories/60", "GET", null },
                    { 62, "https://api.bookbeat.com/api/categories/60/books?offset=0&limit=50", "GET", "Books" },
                    { 63, "https://api.bookbeat.com/api/categoryviews/60?offset=0&limit=50", "GET", null },
                    { 64, "https://api.bookbeat.com/api/categories/61", "GET", null },
                    { 65, "https://api.bookbeat.com/api/categories/61/books?offset=0&limit=50", "GET", "Books" },
                    { 66, "https://api.bookbeat.com/api/categoryviews/61?offset=0&limit=50", "GET", null },
                    { 67, "https://api.bookbeat.com/api/categories/62", "GET", null },
                    { 68, "https://api.bookbeat.com/api/categories/62/books?offset=0&limit=50", "GET", "Books" },
                    { 69, "https://api.bookbeat.com/api/categoryviews/62?offset=0&limit=50", "GET", null },
                    { 70, "https://api.bookbeat.com/api/categories/63", "GET", null },
                    { 71, "https://api.bookbeat.com/api/categories/63/books?offset=0&limit=50", "GET", "Books" },
                    { 72, "https://api.bookbeat.com/api/categoryviews/63?offset=0&limit=50", "GET", null },
                    { 73, "https://api.bookbeat.com/api/categories/64", "GET", null },
                    { 74, "https://api.bookbeat.com/api/categories/64/books?offset=0&limit=50", "GET", "Books" },
                    { 75, "https://api.bookbeat.com/api/categoryviews/64?offset=0&limit=50", "GET", null },
                    { 76, "https://api.bookbeat.com/api/categories/65", "GET", null },
                    { 77, "https://api.bookbeat.com/api/categories/65/books?offset=0&limit=50", "GET", "Books" },
                    { 78, "https://api.bookbeat.com/api/categoryviews/65?offset=0&limit=50", "GET", null },
                    { 79, "https://api.bookbeat.com/api/categories/66", "GET", null },
                    { 80, "https://api.bookbeat.com/api/categories/66/books?offset=0&limit=50", "GET", "Books" },
                    { 81, "https://api.bookbeat.com/api/categoryviews/66?offset=0&limit=50", "GET", null },
                    { 82, "https://api.bookbeat.com/api/categories/67", "GET", null },
                    { 83, "https://api.bookbeat.com/api/categories/67/books?offset=0&limit=50", "GET", "Books" },
                    { 84, "https://api.bookbeat.com/api/categoryviews/67?offset=0&limit=50", "GET", null },
                    { 85, "https://api.bookbeat.com/api/categories/68", "GET", null },
                    { 86, "https://api.bookbeat.com/api/categories/68/books?offset=0&limit=50", "GET", "Books" },
                    { 87, "https://api.bookbeat.com/api/categoryviews/68?offset=0&limit=50", "GET", null },
                    { 88, "https://api.bookbeat.com/api/categories/27", "GET", null },
                    { 89, "https://api.bookbeat.com/api/categories/27/books?offset=0&limit=50", "GET", "Books" },
                    { 90, "https://api.bookbeat.com/api/categoryviews/27?offset=0&limit=50", "GET", null },
                    { 91, "https://api.bookbeat.com/api/categories/30", "GET", null },
                    { 92, "https://api.bookbeat.com/api/categories/30/books?offset=0&limit=50", "GET", "Books" },
                    { 93, "https://api.bookbeat.com/api/categoryviews/30?offset=0&limit=50", "GET", null },
                    { 94, "https://api.bookbeat.com/api/categories/32", "GET", null },
                    { 95, "https://api.bookbeat.com/api/categories/32/books?offset=0&limit=50", "GET", "Books" },
                    { 96, "https://api.bookbeat.com/api/categoryviews/32?offset=0&limit=50", "GET", null },
                    { 97, "https://api.bookbeat.com/api/categories/33", "GET", null },
                    { 98, "https://api.bookbeat.com/api/categories/33/books?offset=0&limit=50", "GET", "Books" },
                    { 99, "https://api.bookbeat.com/api/categoryviews/33?offset=0&limit=50", "GET", null },
                    { 100, "https://api.bookbeat.com/api/categories/48", "GET", null },
                    { 101, "https://api.bookbeat.com/api/categories/48/books?offset=0&limit=50", "GET", "Books" },
                    { 102, "https://api.bookbeat.com/api/categoryviews/48?offset=0&limit=50", "GET", null },
                    { 103, "https://api.bookbeat.com/api/categories/49", "GET", null },
                    { 104, "https://api.bookbeat.com/api/categories/49/books?offset=0&limit=50", "GET", "Books" },
                    { 105, "https://api.bookbeat.com/api/categoryviews/49?offset=0&limit=50", "GET", null },
                    { 106, "https://api.bookbeat.com/api/categories/50", "GET", null },
                    { 107, "https://api.bookbeat.com/api/categories/50/books?offset=0&limit=50", "GET", "Books" },
                    { 108, "https://api.bookbeat.com/api/categoryviews/50?offset=0&limit=50", "GET", null },
                    { 109, "https://api.bookbeat.com/api/categories/51", "GET", null },
                    { 110, "https://api.bookbeat.com/api/categories/51/books?offset=0&limit=50", "GET", "Books" },
                    { 111, "https://api.bookbeat.com/api/categoryviews/51?offset=0&limit=50", "GET", null },
                    { 112, "https://api.bookbeat.com/api/categories/52", "GET", null },
                    { 113, "https://api.bookbeat.com/api/categories/52/books?offset=0&limit=50", "GET", "Books" },
                    { 114, "https://api.bookbeat.com/api/categoryviews/52?offset=0&limit=50", "GET", null },
                    { 115, "https://api.bookbeat.com/api/categories/53", "GET", null },
                    { 116, "https://api.bookbeat.com/api/categories/53/books?offset=0&limit=50", "GET", "Books" },
                    { 117, "https://api.bookbeat.com/api/categoryviews/53?offset=0&limit=50", "GET", null },
                    { 118, "https://api.bookbeat.com/api/categories/20", "GET", null },
                    { 119, "https://api.bookbeat.com/api/categories/20/books?offset=0&limit=50", "GET", "Books" },
                    { 120, "https://api.bookbeat.com/api/categoryviews/20?offset=0&limit=50", "GET", null },
                    { 121, "https://api.bookbeat.com/api/categories/162", "GET", null },
                    { 122, "https://api.bookbeat.com/api/categories/162/books?offset=0&limit=50", "GET", "Books" },
                    { 123, "https://api.bookbeat.com/api/categoryviews/162?offset=0&limit=50", "GET", null },
                    { 124, "https://api.bookbeat.com/api/categories/22", "GET", null },
                    { 125, "https://api.bookbeat.com/api/categories/22/books?offset=0&limit=50", "GET", "Books" },
                    { 126, "https://api.bookbeat.com/api/categoryviews/22?offset=0&limit=50", "GET", null },
                    { 127, "https://api.bookbeat.com/api/categories/23", "GET", null },
                    { 128, "https://api.bookbeat.com/api/categories/23/books?offset=0&limit=50", "GET", "Books" },
                    { 129, "https://api.bookbeat.com/api/categoryviews/23?offset=0&limit=50", "GET", null },
                    { 130, "https://api.bookbeat.com/api/categories/84", "GET", null },
                    { 131, "https://api.bookbeat.com/api/categories/84/books?offset=0&limit=50", "GET", "Books" },
                    { 132, "https://api.bookbeat.com/api/categoryviews/84?offset=0&limit=50", "GET", null },
                    { 133, "https://api.bookbeat.com/api/categories/85", "GET", null },
                    { 134, "https://api.bookbeat.com/api/categories/85/books?offset=0&limit=50", "GET", "Books" },
                    { 135, "https://api.bookbeat.com/api/categoryviews/85?offset=0&limit=50", "GET", null },
                    { 136, "https://api.bookbeat.com/api/categories/86", "GET", null },
                    { 137, "https://api.bookbeat.com/api/categories/86/books?offset=0&limit=50", "GET", "Books" },
                    { 138, "https://api.bookbeat.com/api/categoryviews/86?offset=0&limit=50", "GET", null },
                    { 139, "https://api.bookbeat.com/api/categories/87", "GET", null },
                    { 140, "https://api.bookbeat.com/api/categories/87/books?offset=0&limit=50", "GET", "Books" },
                    { 141, "https://api.bookbeat.com/api/categoryviews/87?offset=0&limit=50", "GET", null },
                    { 142, "https://api.bookbeat.com/api/categories/88", "GET", null },
                    { 143, "https://api.bookbeat.com/api/categories/88/books?offset=0&limit=50", "GET", "Books" },
                    { 144, "https://api.bookbeat.com/api/categoryviews/88?offset=0&limit=50", "GET", null },
                    { 145, "https://api.bookbeat.com/api/categories/89", "GET", null },
                    { 146, "https://api.bookbeat.com/api/categories/89/books?offset=0&limit=50", "GET", "Books" },
                    { 147, "https://api.bookbeat.com/api/categoryviews/89?offset=0&limit=50", "GET", null },
                    { 148, "https://api.bookbeat.com/api/categories/90", "GET", null },
                    { 149, "https://api.bookbeat.com/api/categories/90/books?offset=0&limit=50", "GET", "Books" },
                    { 150, "https://api.bookbeat.com/api/categoryviews/90?offset=0&limit=50", "GET", null },
                    { 151, "https://api.bookbeat.com/api/categories/91", "GET", null },
                    { 152, "https://api.bookbeat.com/api/categories/91/books?offset=0&limit=50", "GET", "Books" },
                    { 153, "https://api.bookbeat.com/api/categoryviews/91?offset=0&limit=50", "GET", null },
                    { 154, "https://api.bookbeat.com/api/categories/92", "GET", null },
                    { 155, "https://api.bookbeat.com/api/categories/92/books?offset=0&limit=50", "GET", "Books" },
                    { 156, "https://api.bookbeat.com/api/categoryviews/92?offset=0&limit=50", "GET", null },
                    { 157, "https://api.bookbeat.com/api/categories/93", "GET", null },
                    { 158, "https://api.bookbeat.com/api/categories/93/books?offset=0&limit=50", "GET", "Books" },
                    { 159, "https://api.bookbeat.com/api/categoryviews/93?offset=0&limit=50", "GET", null },
                    { 160, "https://api.bookbeat.com/api/categories/94", "GET", null },
                    { 161, "https://api.bookbeat.com/api/categories/94/books?offset=0&limit=50", "GET", "Books" },
                    { 162, "https://api.bookbeat.com/api/categoryviews/94?offset=0&limit=50", "GET", null },
                    { 163, "https://api.bookbeat.com/api/categories/95", "GET", null },
                    { 164, "https://api.bookbeat.com/api/categories/95/books?offset=0&limit=50", "GET", "Books" },
                    { 165, "https://api.bookbeat.com/api/categoryviews/95?offset=0&limit=50", "GET", null },
                    { 166, "https://api.bookbeat.com/api/categories/96", "GET", null },
                    { 167, "https://api.bookbeat.com/api/categories/96/books?offset=0&limit=50", "GET", "Books" },
                    { 168, "https://api.bookbeat.com/api/categoryviews/96?offset=0&limit=50", "GET", null },
                    { 169, "https://api.bookbeat.com/api/categories/97", "GET", null },
                    { 170, "https://api.bookbeat.com/api/categories/97/books?offset=0&limit=50", "GET", "Books" },
                    { 171, "https://api.bookbeat.com/api/categoryviews/97?offset=0&limit=50", "GET", null },
                    { 172, "https://api.bookbeat.com/api/categories/38", "GET", null },
                    { 173, "https://api.bookbeat.com/api/categories/38/books?offset=0&limit=50", "GET", "Books" },
                    { 174, "https://api.bookbeat.com/api/categoryviews/38?offset=0&limit=50", "GET", null },
                    { 175, "https://api.bookbeat.com/api/categories/41", "GET", null },
                    { 176, "https://api.bookbeat.com/api/categories/41/books?offset=0&limit=50", "GET", "Books" },
                    { 177, "https://api.bookbeat.com/api/categoryviews/41?offset=0&limit=50", "GET", null },
                    { 178, "https://api.bookbeat.com/api/categories/43", "GET", null },
                    { 179, "https://api.bookbeat.com/api/categories/43/books?offset=0&limit=50", "GET", "Books" },
                    { 180, "https://api.bookbeat.com/api/categoryviews/43?offset=0&limit=50", "GET", null },
                    { 181, "https://api.bookbeat.com/api/categories/45", "GET", null },
                    { 182, "https://api.bookbeat.com/api/categories/45/books?offset=0&limit=50", "GET", "Books" },
                    { 183, "https://api.bookbeat.com/api/categoryviews/45?offset=0&limit=50", "GET", null },
                    { 184, "https://api.bookbeat.com/api/categories/47", "GET", null },
                    { 185, "https://api.bookbeat.com/api/categories/47/books?offset=0&limit=50", "GET", "Books" },
                    { 186, "https://api.bookbeat.com/api/categoryviews/47?offset=0&limit=50", "GET", null },
                    { 187, "https://api.bookbeat.com/api/categories/98", "GET", null },
                    { 188, "https://api.bookbeat.com/api/categories/98/books?offset=0&limit=50", "GET", "Books" },
                    { 189, "https://api.bookbeat.com/api/categoryviews/98?offset=0&limit=50", "GET", null },
                    { 190, "https://api.bookbeat.com/api/categories/99", "GET", null },
                    { 191, "https://api.bookbeat.com/api/categories/99/books?offset=0&limit=50", "GET", "Books" },
                    { 192, "https://api.bookbeat.com/api/categoryviews/99?offset=0&limit=50", "GET", null },
                    { 193, "https://api.bookbeat.com/api/categories/100", "GET", null },
                    { 194, "https://api.bookbeat.com/api/categories/100/books?offset=0&limit=50", "GET", "Books" },
                    { 195, "https://api.bookbeat.com/api/categoryviews/100?offset=0&limit=50", "GET", null },
                    { 196, "https://api.bookbeat.com/api/categories/101", "GET", null },
                    { 197, "https://api.bookbeat.com/api/categories/101/books?offset=0&limit=50", "GET", "Books" },
                    { 198, "https://api.bookbeat.com/api/categoryviews/101?offset=0&limit=50", "GET", null },
                    { 199, "https://api.bookbeat.com/api/categories/102", "GET", null },
                    { 200, "https://api.bookbeat.com/api/categories/102/books?offset=0&limit=50", "GET", "Books" },
                    { 201, "https://api.bookbeat.com/api/categoryviews/102?offset=0&limit=50", "GET", null },
                    { 202, "https://api.bookbeat.com/api/categories/103", "GET", null },
                    { 203, "https://api.bookbeat.com/api/categories/103/books?offset=0&limit=50", "GET", "Books" },
                    { 204, "https://api.bookbeat.com/api/categoryviews/103?offset=0&limit=50", "GET", null },
                    { 205, "https://api.bookbeat.com/api/categories/105", "GET", null },
                    { 206, "https://api.bookbeat.com/api/categories/105/books?offset=0&limit=50", "GET", "Books" },
                    { 207, "https://api.bookbeat.com/api/categoryviews/105?offset=0&limit=50", "GET", null },
                    { 208, "https://api.bookbeat.com/api/categories/34", "GET", null },
                    { 209, "https://api.bookbeat.com/api/categories/34/books?offset=0&limit=50", "GET", "Books" },
                    { 210, "https://api.bookbeat.com/api/categoryviews/34?offset=0&limit=50", "GET", null },
                    { 211, "https://api.bookbeat.com/api/categories/36", "GET", null },
                    { 212, "https://api.bookbeat.com/api/categories/36/books?offset=0&limit=50", "GET", "Books" },
                    { 213, "https://api.bookbeat.com/api/categoryviews/36?offset=0&limit=50", "GET", null },
                    { 214, "https://api.bookbeat.com/api/categories/37", "GET", null },
                    { 215, "https://api.bookbeat.com/api/categories/37/books?offset=0&limit=50", "GET", "Books" },
                    { 216, "https://api.bookbeat.com/api/categoryviews/37?offset=0&limit=50", "GET", null },
                    { 217, "https://api.bookbeat.com/api/categories/73", "GET", null },
                    { 218, "https://api.bookbeat.com/api/categories/73/books?offset=0&limit=50", "GET", "Books" },
                    { 219, "https://api.bookbeat.com/api/categoryviews/73?offset=0&limit=50", "GET", null },
                    { 220, "https://api.bookbeat.com/api/categories/24", "GET", null },
                    { 221, "https://api.bookbeat.com/api/categories/24/books?offset=0&limit=50", "GET", "Books" },
                    { 222, "https://api.bookbeat.com/api/categoryviews/24?offset=0&limit=50", "GET", null },
                    { 223, "https://api.bookbeat.com/api/categories/155", "GET", null },
                    { 224, "https://api.bookbeat.com/api/categories/155/books?offset=0&limit=50", "GET", "Books" },
                    { 225, "https://api.bookbeat.com/api/categoryviews/155?offset=0&limit=50", "GET", null },
                    { 226, "https://api.bookbeat.com/api/categories/156", "GET", null },
                    { 227, "https://api.bookbeat.com/api/categories/156/books?offset=0&limit=50", "GET", "Books" },
                    { 228, "https://api.bookbeat.com/api/categoryviews/156?offset=0&limit=50", "GET", null },
                    { 229, "https://api.bookbeat.com/api/categories/157", "GET", null },
                    { 230, "https://api.bookbeat.com/api/categories/157/books?offset=0&limit=50", "GET", "Books" },
                    { 231, "https://api.bookbeat.com/api/categoryviews/157?offset=0&limit=50", "GET", null },
                    { 232, "https://api.bookbeat.com/api/categories/158", "GET", null },
                    { 233, "https://api.bookbeat.com/api/categories/158/books?offset=0&limit=50", "GET", "Books" },
                    { 234, "https://api.bookbeat.com/api/categoryviews/158?offset=0&limit=50", "GET", null },
                    { 235, "https://api.bookbeat.com/api/categories/159", "GET", null },
                    { 236, "https://api.bookbeat.com/api/categories/159/books?offset=0&limit=50", "GET", "Books" },
                    { 237, "https://api.bookbeat.com/api/categoryviews/159?offset=0&limit=50", "GET", null },
                    { 238, "https://api.bookbeat.com/api/categories/112", "GET", null },
                    { 239, "https://api.bookbeat.com/api/categories/112/books?offset=0&limit=50", "GET", "Books" },
                    { 240, "https://api.bookbeat.com/api/categoryviews/112?offset=0&limit=50", "GET", null },
                    { 241, "https://api.bookbeat.com/api/categories/113", "GET", null },
                    { 242, "https://api.bookbeat.com/api/categories/113/books?offset=0&limit=50", "GET", "Books" },
                    { 243, "https://api.bookbeat.com/api/categoryviews/113?offset=0&limit=50", "GET", null },
                    { 244, "https://api.bookbeat.com/api/categories/114", "GET", null },
                    { 245, "https://api.bookbeat.com/api/categories/114/books?offset=0&limit=50", "GET", "Books" },
                    { 246, "https://api.bookbeat.com/api/categoryviews/114?offset=0&limit=50", "GET", null },
                    { 247, "https://api.bookbeat.com/api/categories/115", "GET", null },
                    { 248, "https://api.bookbeat.com/api/categories/115/books?offset=0&limit=50", "GET", "Books" },
                    { 249, "https://api.bookbeat.com/api/categoryviews/115?offset=0&limit=50", "GET", null },
                    { 250, "https://api.bookbeat.com/api/categories/116", "GET", null },
                    { 251, "https://api.bookbeat.com/api/categories/116/books?offset=0&limit=50", "GET", "Books" },
                    { 252, "https://api.bookbeat.com/api/categoryviews/116?offset=0&limit=50", "GET", null },
                    { 253, "https://api.bookbeat.com/api/categories/117", "GET", null },
                    { 254, "https://api.bookbeat.com/api/categories/117/books?offset=0&limit=50", "GET", "Books" },
                    { 255, "https://api.bookbeat.com/api/categoryviews/117?offset=0&limit=50", "GET", null },
                    { 256, "https://api.bookbeat.com/api/categories/118", "GET", null },
                    { 257, "https://api.bookbeat.com/api/categories/118/books?offset=0&limit=50", "GET", "Books" },
                    { 258, "https://api.bookbeat.com/api/categoryviews/118?offset=0&limit=50", "GET", null },
                    { 259, "https://api.bookbeat.com/api/categories/119", "GET", null },
                    { 260, "https://api.bookbeat.com/api/categories/119/books?offset=0&limit=50", "GET", "Books" },
                    { 261, "https://api.bookbeat.com/api/categoryviews/119?offset=0&limit=50", "GET", null },
                    { 262, "https://api.bookbeat.com/api/categories/120", "GET", null },
                    { 263, "https://api.bookbeat.com/api/categories/120/books?offset=0&limit=50", "GET", "Books" },
                    { 264, "https://api.bookbeat.com/api/categoryviews/120?offset=0&limit=50", "GET", null },
                    { 265, "https://api.bookbeat.com/api/categories/121", "GET", null },
                    { 266, "https://api.bookbeat.com/api/categories/121/books?offset=0&limit=50", "GET", "Books" },
                    { 267, "https://api.bookbeat.com/api/categoryviews/121?offset=0&limit=50", "GET", null },
                    { 268, "https://api.bookbeat.com/api/categories/122", "GET", null },
                    { 269, "https://api.bookbeat.com/api/categories/122/books?offset=0&limit=50", "GET", "Books" },
                    { 270, "https://api.bookbeat.com/api/categoryviews/122?offset=0&limit=50", "GET", null },
                    { 271, "https://api.bookbeat.com/api/categories/123", "GET", null },
                    { 272, "https://api.bookbeat.com/api/categories/123/books?offset=0&limit=50", "GET", "Books" },
                    { 273, "https://api.bookbeat.com/api/categoryviews/123?offset=0&limit=50", "GET", null },
                    { 274, "https://api.bookbeat.com/api/categories/124", "GET", null },
                    { 275, "https://api.bookbeat.com/api/categories/124/books?offset=0&limit=50", "GET", "Books" },
                    { 276, "https://api.bookbeat.com/api/categoryviews/124?offset=0&limit=50", "GET", null },
                    { 277, "https://api.bookbeat.com/api/categories/125", "GET", null },
                    { 278, "https://api.bookbeat.com/api/categories/125/books?offset=0&limit=50", "GET", "Books" },
                    { 279, "https://api.bookbeat.com/api/categoryviews/125?offset=0&limit=50", "GET", null },
                    { 280, "https://api.bookbeat.com/api/categories/126", "GET", null },
                    { 281, "https://api.bookbeat.com/api/categories/126/books?offset=0&limit=50", "GET", "Books" },
                    { 282, "https://api.bookbeat.com/api/categoryviews/126?offset=0&limit=50", "GET", null },
                    { 283, "https://api.bookbeat.com/api/categories/127", "GET", null },
                    { 284, "https://api.bookbeat.com/api/categories/127/books?offset=0&limit=50", "GET", "Books" },
                    { 285, "https://api.bookbeat.com/api/categoryviews/127?offset=0&limit=50", "GET", null },
                    { 286, "https://api.bookbeat.com/api/categories/128", "GET", null },
                    { 287, "https://api.bookbeat.com/api/categories/128/books?offset=0&limit=50", "GET", "Books" },
                    { 288, "https://api.bookbeat.com/api/categoryviews/128?offset=0&limit=50", "GET", null },
                    { 289, "https://api.bookbeat.com/api/categories/129", "GET", null },
                    { 290, "https://api.bookbeat.com/api/categories/129/books?offset=0&limit=50", "GET", "Books" },
                    { 291, "https://api.bookbeat.com/api/categoryviews/129?offset=0&limit=50", "GET", null },
                    { 292, "https://api.bookbeat.com/api/categories/130", "GET", null },
                    { 293, "https://api.bookbeat.com/api/categories/130/books?offset=0&limit=50", "GET", "Books" },
                    { 294, "https://api.bookbeat.com/api/categoryviews/130?offset=0&limit=50", "GET", null },
                    { 295, "https://api.bookbeat.com/api/categories/131", "GET", null },
                    { 296, "https://api.bookbeat.com/api/categories/131/books?offset=0&limit=50", "GET", "Books" },
                    { 297, "https://api.bookbeat.com/api/categoryviews/131?offset=0&limit=50", "GET", null },
                    { 298, "https://api.bookbeat.com/api/categories/132", "GET", null },
                    { 299, "https://api.bookbeat.com/api/categories/132/books?offset=0&limit=50", "GET", "Books" },
                    { 300, "https://api.bookbeat.com/api/categoryviews/132?offset=0&limit=50", "GET", null },
                    { 301, "https://api.bookbeat.com/api/categories/133", "GET", null },
                    { 302, "https://api.bookbeat.com/api/categories/133/books?offset=0&limit=50", "GET", "Books" },
                    { 303, "https://api.bookbeat.com/api/categoryviews/133?offset=0&limit=50", "GET", null },
                    { 304, "https://api.bookbeat.com/api/categories/134", "GET", null },
                    { 305, "https://api.bookbeat.com/api/categories/134/books?offset=0&limit=50", "GET", "Books" },
                    { 306, "https://api.bookbeat.com/api/categoryviews/134?offset=0&limit=50", "GET", null },
                    { 307, "https://api.bookbeat.com/api/categories/135", "GET", null },
                    { 308, "https://api.bookbeat.com/api/categories/135/books?offset=0&limit=50", "GET", "Books" },
                    { 309, "https://api.bookbeat.com/api/categoryviews/135?offset=0&limit=50", "GET", null },
                    { 310, "https://api.bookbeat.com/api/categories/136", "GET", null },
                    { 311, "https://api.bookbeat.com/api/categories/136/books?offset=0&limit=50", "GET", "Books" },
                    { 312, "https://api.bookbeat.com/api/categoryviews/136?offset=0&limit=50", "GET", null },
                    { 313, "https://api.bookbeat.com/api/categories/137", "GET", null },
                    { 314, "https://api.bookbeat.com/api/categories/137/books?offset=0&limit=50", "GET", "Books" },
                    { 315, "https://api.bookbeat.com/api/categoryviews/137?offset=0&limit=50", "GET", null },
                    { 316, "https://api.bookbeat.com/api/categories/138", "GET", null },
                    { 317, "https://api.bookbeat.com/api/categories/138/books?offset=0&limit=50", "GET", "Books" },
                    { 318, "https://api.bookbeat.com/api/categoryviews/138?offset=0&limit=50", "GET", null },
                    { 319, "https://api.bookbeat.com/api/categories/139", "GET", null },
                    { 320, "https://api.bookbeat.com/api/categories/139/books?offset=0&limit=50", "GET", "Books" },
                    { 321, "https://api.bookbeat.com/api/categoryviews/139?offset=0&limit=50", "GET", null },
                    { 322, "https://api.bookbeat.com/api/categories/140", "GET", null },
                    { 323, "https://api.bookbeat.com/api/categories/140/books?offset=0&limit=50", "GET", "Books" },
                    { 324, "https://api.bookbeat.com/api/categoryviews/140?offset=0&limit=50", "GET", null },
                    { 325, "https://api.bookbeat.com/api/categories/141", "GET", null },
                    { 326, "https://api.bookbeat.com/api/categories/141/books?offset=0&limit=50", "GET", "Books" },
                    { 327, "https://api.bookbeat.com/api/categoryviews/141?offset=0&limit=50", "GET", null },
                    { 328, "https://api.bookbeat.com/api/categories/142", "GET", null },
                    { 329, "https://api.bookbeat.com/api/categories/142/books?offset=0&limit=50", "GET", "Books" },
                    { 330, "https://api.bookbeat.com/api/categoryviews/142?offset=0&limit=50", "GET", null },
                    { 331, "https://api.bookbeat.com/api/categories/143", "GET", null },
                    { 332, "https://api.bookbeat.com/api/categories/143/books?offset=0&limit=50", "GET", "Books" },
                    { 333, "https://api.bookbeat.com/api/categoryviews/143?offset=0&limit=50", "GET", null },
                    { 334, "https://api.bookbeat.com/api/categories/144", "GET", null },
                    { 335, "https://api.bookbeat.com/api/categories/144/books?offset=0&limit=50", "GET", "Books" },
                    { 336, "https://api.bookbeat.com/api/categoryviews/144?offset=0&limit=50", "GET", null },
                    { 337, "https://api.bookbeat.com/api/categories/145", "GET", null },
                    { 338, "https://api.bookbeat.com/api/categories/145/books?offset=0&limit=50", "GET", "Books" },
                    { 339, "https://api.bookbeat.com/api/categoryviews/145?offset=0&limit=50", "GET", null },
                    { 340, "https://api.bookbeat.com/api/categories/146", "GET", null },
                    { 341, "https://api.bookbeat.com/api/categories/146/books?offset=0&limit=50", "GET", "Books" },
                    { 342, "https://api.bookbeat.com/api/categoryviews/146?offset=0&limit=50", "GET", null },
                    { 343, "https://api.bookbeat.com/api/categories/147", "GET", null },
                    { 344, "https://api.bookbeat.com/api/categories/147/books?offset=0&limit=50", "GET", "Books" },
                    { 345, "https://api.bookbeat.com/api/categoryviews/147?offset=0&limit=50", "GET", null },
                    { 346, "https://api.bookbeat.com/api/categories/148", "GET", null },
                    { 347, "https://api.bookbeat.com/api/categories/148/books?offset=0&limit=50", "GET", "Books" },
                    { 348, "https://api.bookbeat.com/api/categoryviews/148?offset=0&limit=50", "GET", null },
                    { 349, "https://api.bookbeat.com/api/categories/149", "GET", null },
                    { 350, "https://api.bookbeat.com/api/categories/149/books?offset=0&limit=50", "GET", "Books" },
                    { 351, "https://api.bookbeat.com/api/categoryviews/149?offset=0&limit=50", "GET", null },
                    { 352, "https://api.bookbeat.com/api/categories/150", "GET", null },
                    { 353, "https://api.bookbeat.com/api/categories/150/books?offset=0&limit=50", "GET", "Books" },
                    { 354, "https://api.bookbeat.com/api/categoryviews/150?offset=0&limit=50", "GET", null },
                    { 355, "https://api.bookbeat.com/api/categories/151", "GET", null },
                    { 356, "https://api.bookbeat.com/api/categories/151/books?offset=0&limit=50", "GET", "Books" },
                    { 357, "https://api.bookbeat.com/api/categoryviews/151?offset=0&limit=50", "GET", null },
                    { 358, "https://api.bookbeat.com/api/categories/152", "GET", null },
                    { 359, "https://api.bookbeat.com/api/categories/152/books?offset=0&limit=50", "GET", "Books" },
                    { 360, "https://api.bookbeat.com/api/categoryviews/152?offset=0&limit=50", "GET", null },
                    { 361, "https://api.bookbeat.com/api/categories/153", "GET", null },
                    { 362, "https://api.bookbeat.com/api/categories/153/books?offset=0&limit=50", "GET", "Books" },
                    { 363, "https://api.bookbeat.com/api/categoryviews/153?offset=0&limit=50", "GET", null },
                    { 364, "https://api.bookbeat.com/api/categories/165", "GET", null },
                    { 365, "https://api.bookbeat.com/api/categories/165/books?offset=0&limit=50", "GET", "Books" },
                    { 366, "https://api.bookbeat.com/api/categoryviews/165?offset=0&limit=50", "GET", null },
                    { 367, "https://api.bookbeat.com/api/categories/167", "GET", null },
                    { 368, "https://api.bookbeat.com/api/categories/167/books?offset=0&limit=50", "GET", "Books" },
                    { 369, "https://api.bookbeat.com/api/categoryviews/167?offset=0&limit=50", "GET", null },
                    { 370, "https://api.bookbeat.com/api/categories/168", "GET", null },
                    { 371, "https://api.bookbeat.com/api/categories/168/books?offset=0&limit=50", "GET", "Books" },
                    { 372, "https://api.bookbeat.com/api/categoryviews/168?offset=0&limit=50", "GET", null },
                    { 373, "https://api.bookbeat.com/api/categories/170", "GET", null },
                    { 374, "https://api.bookbeat.com/api/categories/170/books?offset=0&limit=50", "GET", "Books" },
                    { 375, "https://api.bookbeat.com/api/categoryviews/170?offset=0&limit=50", "GET", null },
                    { 376, "https://api.bookbeat.com/api/categories/171", "GET", null },
                    { 377, "https://api.bookbeat.com/api/categories/171/books?offset=0&limit=50", "GET", "Books" },
                    { 378, "https://api.bookbeat.com/api/categoryviews/171?offset=0&limit=50", "GET", null },
                    { 379, "https://api.bookbeat.com/api/categories/166", "GET", null },
                    { 380, "https://api.bookbeat.com/api/categories/166/books?offset=0&limit=50", "GET", "Books" },
                    { 381, "https://api.bookbeat.com/api/categoryviews/166?offset=0&limit=50", "GET", null },
                    { 382, "https://api.bookbeat.com/api/categories/172", "GET", null },
                    { 383, "https://api.bookbeat.com/api/categories/172/books?offset=0&limit=50", "GET", "Books" },
                    { 384, "https://api.bookbeat.com/api/categoryviews/172?offset=0&limit=50", "GET", null },
                    { 385, "https://api.bookbeat.com/api/categories/173", "GET", null },
                    { 386, "https://api.bookbeat.com/api/categories/173/books?offset=0&limit=50", "GET", "Books" },
                    { 387, "https://api.bookbeat.com/api/categoryviews/173?offset=0&limit=50", "GET", null },
                    { 388, "https://api.bookbeat.com/api/categories/174", "GET", null },
                    { 389, "https://api.bookbeat.com/api/categories/174/books?offset=0&limit=50", "GET", "Books" },
                    { 390, "https://api.bookbeat.com/api/categoryviews/174?offset=0&limit=50", "GET", null },
                    { 391, "https://api.bookbeat.com/api/categories/175", "GET", null },
                    { 392, "https://api.bookbeat.com/api/categories/175/books?offset=0&limit=50", "GET", "Books" },
                    { 393, "https://api.bookbeat.com/api/categoryviews/175?offset=0&limit=50", "GET", null },
                    { 394, "https://api.bookbeat.com/api/categories/176", "GET", null },
                    { 395, "https://api.bookbeat.com/api/categories/176/books?offset=0&limit=50", "GET", "Books" },
                    { 396, "https://api.bookbeat.com/api/categoryviews/176?offset=0&limit=50", "GET", null }
                });

            migrationBuilder.InsertData(
                table: "Categories",
                columns: new[] { "Id", "Image", "ParentId", "Title" },
                values: new object[,]
                {
                    { 5, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_899.png?format=png&quality=75&w=450", 2, "Historical Novels" },
                    { 6, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_4.png?format=png&quality=75&w=450", 2, "Feel-Good Novels" },
                    { 8, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_85.png?format=png&quality=75&w=450", 2, "Contemporary Novels" },
                    { 11, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_25.png?format=png&quality=75&w=450", 2, "War Novels" },
                    { 13, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_14.png?format=png&quality=75&w=450", 12, "Thrillers" },
                    { 14, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_81.png?format=png&quality=75&w=450", 12, "Psychological Thrillers" },
                    { 15, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_9.png?format=png&quality=75&w=450", 12, "Crime Fiction" },
                    { 16, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_13.png?format=png&quality=75&w=450", 12, "Classic Crime & Mystery Fiction" },
                    { 17, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_11.png?format=png&quality=75&w=450", 12, "Cosy Crime" },
                    { 22, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_32.png?format=png&quality=75&w=450", 20, "Romantic Fantasy" },
                    { 23, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_41.png?format=png&quality=75&w=450", 20, "Horror" },
                    { 30, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_99.png?format=png&quality=75&w=450", 27, "Hot Romance" },
                    { 32, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_98.png?format=png&quality=75&w=450", 27, "Romantic Suspense" },
                    { 33, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_988.png?format=png&quality=75&w=450", 27, "Historical Romance" },
                    { 36, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_72.png?format=png&quality=75&w=450", 34, "Humoristic Novels" },
                    { 37, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_10.png?format=png&quality=75&w=450", 34, "Parody & Satire" },
                    { 41, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_51.png?format=png&quality=75&w=450", 38, "Relationships & Families" },
                    { 43, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_94.png?format=png&quality=75&w=450", 38, "Popular Psychology" },
                    { 45, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_96.png?format=png&quality=75&w=450", 38, "Health & Fitness" },
                    { 47, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_95.png?format=png&quality=75&w=450", 38, "Mindfulness & Spirituality" },
                    { 49, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_73.png?format=png&quality=75&w=450", 48, "Autobiographies & Memoirs" },
                    { 50, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_34.png?format=png&quality=75&w=450", 48, "Political & Societal Biographies" },
                    { 51, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_322.png?format=png&quality=75&w=450", 48, "Royal Biographies" },
                    { 52, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_45.png?format=png&quality=75&w=450", 48, "Art & Literary Biographies" },
                    { 53, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_78.png?format=png&quality=75&w=450", 48, "Religious & Philosofical Biographie" },
                    { 55, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_82.png?format=png&quality=75&w=450", 54, "True Crime" },
                    { 56, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_31.png?format=png&quality=75&w=450", 54, "Music & Films" },
                    { 57, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_83.png?format=png&quality=75&w=450", 54, "Literature & Art" },
                    { 58, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_77.png?format=png&quality=75&w=450", 54, "Language & Linguistics" },
                    { 59, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_24.png?format=png&quality=75&w=450", 54, "Law" },
                    { 60, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_87.png?format=png&quality=75&w=450", 54, "Society & Culture" },
                    { 61, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_94.png?format=png&quality=75&w=450", 54, "Psychology" },
                    { 62, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_844.png?format=png&quality=75&w=450", 54, "Politics & War" },
                    { 63, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_91.png?format=png&quality=75&w=450", 54, "Travelling & Countries" },
                    { 64, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_26.png?format=png&quality=75&w=450", 54, "History" },
                    { 65, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_20.png?format=png&quality=75&w=450", 54, "Sports" },
                    { 66, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_211.png?format=png&quality=75&w=450", 54, "Nature & Science" },
                    { 67, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_35.png?format=png&quality=75&w=450", 54, "Economics & Finance" },
                    { 68, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_48.png?format=png&quality=75&w=450", 54, "Religion & Philosophy" },
                    { 85, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_55.png?format=png&quality=75&w=450", 84, "Books for Children: 0-36 months" },
                    { 86, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_56.png?format=png&quality=75&w=450", 84, "Books for Children: from 3 years" },
                    { 87, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_54.png?format=png&quality=75&w=450", 84, "Books for Children: from 6 years" },
                    { 88, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_60.png?format=png&quality=75&w=450", 84, "Books for Children: from 9 years" },
                    { 89, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_544.png?format=png&quality=75&w=450", 84, "Classic Books for Children" },
                    { 90, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_50.png?format=png&quality=75&w=450", 84, "Non-Fiction Books for Children" },
                    { 91, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_58.png?format=png&quality=75&w=450", 84, "Fairy Tales for Children" },
                    { 92, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_57.png?format=png&quality=75&w=450", 84, "Animal & Nature Stories for Children" },
                    { 93, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_200.png?format=png&quality=75&w=450", 84, "Sporting Stories for Children" },
                    { 94, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_37.png?format=png&quality=75&w=450", 84, "Adventure Stories for Children" },
                    { 95, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_533.png?format=png&quality=75&w=450", 84, "Fun for kids" },
                    { 96, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_61.png?format=png&quality=75&w=450", 84, "Ghosts & Supernatural for Children" },
                    { 97, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_59.png?format=png&quality=75&w=450", 84, "Love & Friendship for Children" },
                    { 99, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_599.png?format=png&quality=75&w=450", 98, "Books for Young Adults: from 12 years" },
                    { 100, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_63.png?format=png&quality=75&w=450", 98, "Books for Young Adults: from 14 years" },
                    { 101, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_2.png?format=png&quality=75&w=450", 98, "Young love" },
                    { 102, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_8.png?format=png&quality=75&w=450", 98, "Crime Books for Young Adults" },
                    { 103, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_899.png?format=png&quality=75&w=450", 98, "Historical Novels for Young Adults" },
                    { 105, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_36.png?format=png&quality=75&w=450", 98, "Fantasy & Science Fiction for Young Adults" },
                    { 113, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_1.png?format=png&quality=75&w=450", 112, "Romaner" },
                    { 114, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_8.png?format=png&quality=75&w=450", 112, "Spänning" },
                    { 115, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_36.png?format=png&quality=75&w=450", 112, "Fantasy & Science Fiction" },
                    { 116, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_69.png?format=png&quality=75&w=450", 112, "Fakta" },
                    { 117, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_52.png?format=png&quality=75&w=450", 112, "Barn & Ungdom" },
                    { 119, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_1.png?format=png&quality=75&w=450", 118, "Romaanit" },
                    { 120, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_8.png?format=png&quality=75&w=450", 118, "Dekkarit" },
                    { 121, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_36.png?format=png&quality=75&w=450", 118, "Fantasia & Science Fiction" },
                    { 122, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_69.png?format=png&quality=75&w=450", 118, "Tieto" },
                    { 123, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_52.png?format=png&quality=75&w=450", 118, "Lapset & Nuoret" },
                    { 125, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_1.png?format=png&quality=75&w=450", 124, "Romane" },
                    { 126, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_8.png?format=png&quality=75&w=450", 124, "Spannung" },
                    { 127, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_36.png?format=png&quality=75&w=450", 124, "Fantasy & Science Fiction" },
                    { 128, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_69.png?format=png&quality=75&w=450", 124, "Sachbuch" },
                    { 129, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_52.png?format=png&quality=75&w=450", 124, "Kinder & Jugendbuch" },
                    { 131, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_1.png?format=png&quality=75&w=450", 130, "Narrativa" },
                    { 132, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_8.png?format=png&quality=75&w=450", 130, "Thriller" },
                    { 133, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_36.png?format=png&quality=75&w=450", 130, "Fantasy e fantascienza" },
                    { 134, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_69.png?format=png&quality=75&w=450", 130, "Non-fiction" },
                    { 135, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_52.png?format=png&quality=75&w=450", 130, "Bambini" },
                    { 137, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_1.png?format=png&quality=75&w=450", 136, "Ficción" },
                    { 138, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_8.png?format=png&quality=75&w=450", 136, "Negra y criminal" },
                    { 139, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_36.png?format=png&quality=75&w=450", 136, "Narrativa fantástica y novela de ciencia ficción" },
                    { 140, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_69.png?format=png&quality=75&w=450", 136, "No ficción" },
                    { 141, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_52.png?format=png&quality=75&w=450", 136, "Infantil y juvenil" },
                    { 143, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_1.png?format=png&quality=75&w=450", 142, "Skønlitteratur" },
                    { 144, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_8.png?format=png&quality=75&w=450", 142, "Krimi & Spænding" },
                    { 145, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_36.png?format=png&quality=75&w=450", 142, "Sci-fi & Fantasy" },
                    { 146, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_69.png?format=png&quality=75&w=450", 142, "Faglitteratur & Personlig udvikling" },
                    { 147, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_52.png?format=png&quality=75&w=450", 142, "Børnebøger & Ungdom/YA" },
                    { 149, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_1.png?format=png&quality=75&w=450", 148, "Powieści" },
                    { 150, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_8.png?format=png&quality=75&w=450", 148, "Kryminały" },
                    { 151, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_36.png?format=png&quality=75&w=450", 148, "Fantastyka i Sci-fi" },
                    { 152, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_69.png?format=png&quality=75&w=450", 148, "Literatura faktu" },
                    { 153, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_52.png?format=png&quality=75&w=450", 148, "Dla dzieci i młodzieży" },
                    { 156, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_156.png?format=png&quality=75&w=450", 155, "Short Stories" },
                    { 157, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_157.png?format=png&quality=75&w=450", 155, "Comics & Graphic Novels" },
                    { 158, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_158.png?format=png&quality=75&w=450", 155, "Plays & Playscripts" },
                    { 159, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_159.png?format=png&quality=75&w=450", 155, "Poetry" },
                    { 160, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_79.png?format=png&quality=75&w=450", 54, "Food & Drink" },
                    { 161, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_53.png?format=png&quality=75&w=450", 54, "Leisure & Hobbies" },
                    { 162, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_162.png?format=png&quality=75&w=450", 20, "High Fantasy" },
                    { 167, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_1.png?format=png&quality=75&w=450", 165, "Romans" },
                    { 168, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_8.png?format=png&quality=75&w=450", 165, "Misdaad" },
                    { 169, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_36.png?format=png&quality=75&w=450", 165, "Fantasy & Sciencefiction" },
                    { 170, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_69.png?format=png&quality=75&w=450", 165, "Non-fictie" },
                    { 171, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_52.png?format=png&quality=75&w=450", 165, "Kinderboeken & Young Adult" },
                    { 172, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_8.png?format=png&quality=75&w=450", 166, "Crime" },
                    { 173, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_1.png?format=png&quality=75&w=450", 166, "Romans" },
                    { 174, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_69.png?format=png&quality=75&w=450", 166, "Non-fiction" },
                    { 175, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_36.png?format=png&quality=75&w=450", 166, "Fantasy & Science fiction" },
                    { 176, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_52.png?format=png&quality=75&w=450", 166, "Enfants & Young Adult" },
                    { 177, "https://prod-bb-images.akamaized.net/categories-covers/cat/img_cat_177.jpg?format=png&quality=75&w=450", 2, "Family Sagas" }
                });

            migrationBuilder.InsertData(
                table: "Links",
                columns: new[] { "Id", "BooksId", "CategoryId", "DynamicContentId", "SelfId" },
                values: new object[,]
                {
                    { 1, 2, 12, 3, 1 },
                    { 7, 20, 2, 21, 19 },
                    { 13, 38, 54, 39, 37 },
                    { 30, 89, 27, 90, 88 },
                    { 34, 101, 48, 102, 100 },
                    { 40, 119, 20, 120, 118 },
                    { 44, 131, 84, 132, 130 },
                    { 58, 173, 38, 174, 172 },
                    { 63, 188, 98, 189, 187 },
                    { 70, 209, 34, 210, 208 },
                    { 73, 218, 73, 219, 217 },
                    { 74, 221, 24, 222, 220 },
                    { 75, 224, 155, 225, 223 },
                    { 80, 239, 112, 240, 238 },
                    { 86, 257, 118, 258, 256 },
                    { 92, 275, 124, 276, 274 },
                    { 98, 293, 130, 294, 292 },
                    { 104, 311, 136, 312, 310 },
                    { 110, 329, 142, 330, 328 },
                    { 116, 347, 148, 348, 346 },
                    { 122, 365, 165, 366, 364 },
                    { 127, 380, 166, 381, 379 },
                    { 2, 5, 13, 6, 4 },
                    { 3, 8, 14, 9, 7 },
                    { 4, 11, 15, 12, 10 },
                    { 5, 14, 16, 15, 13 },
                    { 6, 17, 17, 18, 16 },
                    { 8, 23, 5, 24, 22 },
                    { 9, 26, 6, 27, 25 },
                    { 10, 29, 8, 30, 28 },
                    { 11, 32, 11, 33, 31 },
                    { 12, 35, 177, 36, 34 },
                    { 14, 41, 160, 42, 40 },
                    { 15, 44, 161, 45, 43 },
                    { 16, 47, 55, 48, 46 },
                    { 17, 50, 56, 51, 49 },
                    { 18, 53, 57, 54, 52 },
                    { 19, 56, 58, 57, 55 },
                    { 20, 59, 59, 60, 58 },
                    { 21, 62, 60, 63, 61 },
                    { 22, 65, 61, 66, 64 },
                    { 23, 68, 62, 69, 67 },
                    { 24, 71, 63, 72, 70 },
                    { 25, 74, 64, 75, 73 },
                    { 26, 77, 65, 78, 76 },
                    { 27, 80, 66, 81, 79 },
                    { 28, 83, 67, 84, 82 },
                    { 29, 86, 68, 87, 85 },
                    { 31, 92, 30, 93, 91 },
                    { 32, 95, 32, 96, 94 },
                    { 33, 98, 33, 99, 97 },
                    { 35, 104, 49, 105, 103 },
                    { 36, 107, 50, 108, 106 },
                    { 37, 110, 51, 111, 109 },
                    { 38, 113, 52, 114, 112 },
                    { 39, 116, 53, 117, 115 },
                    { 41, 122, 162, 123, 121 },
                    { 42, 125, 22, 126, 124 },
                    { 43, 128, 23, 129, 127 },
                    { 45, 134, 85, 135, 133 },
                    { 46, 137, 86, 138, 136 },
                    { 47, 140, 87, 141, 139 },
                    { 48, 143, 88, 144, 142 },
                    { 49, 146, 89, 147, 145 },
                    { 50, 149, 90, 150, 148 },
                    { 51, 152, 91, 153, 151 },
                    { 52, 155, 92, 156, 154 },
                    { 53, 158, 93, 159, 157 },
                    { 54, 161, 94, 162, 160 },
                    { 55, 164, 95, 165, 163 },
                    { 56, 167, 96, 168, 166 },
                    { 57, 170, 97, 171, 169 },
                    { 59, 176, 41, 177, 175 },
                    { 60, 179, 43, 180, 178 },
                    { 61, 182, 45, 183, 181 },
                    { 62, 185, 47, 186, 184 },
                    { 64, 191, 99, 192, 190 },
                    { 65, 194, 100, 195, 193 },
                    { 66, 197, 101, 198, 196 },
                    { 67, 200, 102, 201, 199 },
                    { 68, 203, 103, 204, 202 },
                    { 69, 206, 105, 207, 205 },
                    { 71, 212, 36, 213, 211 },
                    { 72, 215, 37, 216, 214 },
                    { 76, 227, 156, 228, 226 },
                    { 77, 230, 157, 231, 229 },
                    { 78, 233, 158, 234, 232 },
                    { 79, 236, 159, 237, 235 },
                    { 81, 242, 113, 243, 241 },
                    { 82, 245, 114, 246, 244 },
                    { 83, 248, 115, 249, 247 },
                    { 84, 251, 116, 252, 250 },
                    { 85, 254, 117, 255, 253 },
                    { 87, 260, 119, 261, 259 },
                    { 88, 263, 120, 264, 262 },
                    { 89, 266, 121, 267, 265 },
                    { 90, 269, 122, 270, 268 },
                    { 91, 272, 123, 273, 271 },
                    { 93, 278, 125, 279, 277 },
                    { 94, 281, 126, 282, 280 },
                    { 95, 284, 127, 285, 283 },
                    { 96, 287, 128, 288, 286 },
                    { 97, 290, 129, 291, 289 },
                    { 99, 296, 131, 297, 295 },
                    { 100, 299, 132, 300, 298 },
                    { 101, 302, 133, 303, 301 },
                    { 102, 305, 134, 306, 304 },
                    { 103, 308, 135, 309, 307 },
                    { 105, 314, 137, 315, 313 },
                    { 106, 317, 138, 318, 316 },
                    { 107, 320, 139, 321, 319 },
                    { 108, 323, 140, 324, 322 },
                    { 109, 326, 141, 327, 325 },
                    { 111, 332, 143, 333, 331 },
                    { 112, 335, 144, 336, 334 },
                    { 113, 338, 145, 339, 337 },
                    { 114, 341, 146, 342, 340 },
                    { 115, 344, 147, 345, 343 },
                    { 117, 350, 149, 351, 349 },
                    { 118, 353, 150, 354, 352 },
                    { 119, 356, 151, 357, 355 },
                    { 120, 359, 152, 360, 358 },
                    { 121, 362, 153, 363, 361 },
                    { 123, 368, 167, 369, 367 },
                    { 124, 371, 168, 372, 370 },
                    { 125, 374, 170, 375, 373 },
                    { 126, 377, 171, 378, 376 },
                    { 128, 383, 172, 384, 382 },
                    { 129, 386, 173, 387, 385 },
                    { 130, 389, 174, 390, 388 },
                    { 131, 392, 175, 393, 391 },
                    { 132, 395, 176, 396, 394 }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Categories_ParentId",
                table: "Categories",
                column: "ParentId");

            migrationBuilder.CreateIndex(
                name: "IX_Links_BooksId",
                table: "Links",
                column: "BooksId");

            migrationBuilder.CreateIndex(
                name: "IX_Links_CategoryId",
                table: "Links",
                column: "CategoryId",
                unique: true,
                filter: "[CategoryId] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_Links_DynamicContentId",
                table: "Links",
                column: "DynamicContentId");

            migrationBuilder.CreateIndex(
                name: "IX_Links_SelfId",
                table: "Links",
                column: "SelfId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Links");

            migrationBuilder.DropTable(
                name: "Categories");

            migrationBuilder.DropTable(
                name: "LinkObject");
        }
    }
}
