name: Build and Push Docker Image to Docker Hub
on:
  push:
    branches: [ "main" ]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.1
        with:
          versionSpec: '6.0.0'
        
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v3.1.1

      - name: Git Bashing Version
        run: echo ${{ env.GitVersion_SemVer}}

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: segelfartyg/bookapi:${{ env.GitVersion_SemVer}} , segelfartyg/bookapi:latest
